{% set name = "django-picklefield" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-picklefield-{{ version }}.tar.gz
  sha256: 15ccba592ca953b9edf9532e64640329cd47b136b7f8f10f2939caa5f9ce4287

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.0
    - django
    - pip
  run:
    - python >=3.0
    - django >=2.2

test:
  imports:
    - picklefield
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/gintas/django-picklefield
  summary: Pickled object field for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mxr-conda
